# Camunda
# http://localhost:8080/camunda/app/
camunda.bpm:
  admin-user:
    id: demo
    password: masterdemo
    firstName: Demo
  filter:
    create: All tasks
# To See H2 Console in Browser:
# http://localhost:8080/h2-console
spring.h2.console:
  enabled: true

# DB
spring.datasource:
  url: jdbc:h2:mem:camundaBpmnDb
  driverClassName: org.h2.Driver
  username: sa
  password: 111

# JPA / HIBERNATE
spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.H2Dialect